name 'dhoppe-screen'
version '0.1.0'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-screen'
source 'git://github.com/dhoppe/puppet-screen'
summary 'Screen Module'
description 'Screen Module for Debian, Ubuntu'
dependency 'puppetlabs/stdlib', '>=0.0.1'
